"""empty message

Revision ID: 654b2dd3f5d5
Revises: 442e6d023460
Create Date: 2022-08-25 09:31:01.009498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654b2dd3f5d5'
down_revision = '442e6d023460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id_(referred_table_name)s'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_user_id_(referred_table_name)s'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
