"""empty message

Revision ID: 86897eb4bead
Revises: c43e8b613d44
Create Date: 2022-08-25 09:39:16.971483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86897eb4bead'
down_revision = 'c43e8b613d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_answer_user_id_(referred_table_name)s'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_user_id_(referred_table_name)s'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
